/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for Aniiconomy report output
 */
export interface AniiconomyReport {
  /**
   * List of items keyed by item id
   */
  items: {
    [k: string]: Item;
  };
  /**
   * List of trades keyed by trade id
   */
  trades: {
    [k: string]: Trade;
  };
  /**
   * Horizon used for exchange_value_index and fair_prices
   */
  time_horizon: "day" | "week" | "month" | "season";
  /**
   * item id -> fair price in money
   */
  fair_prices: {
    [k: string]: number;
  };
  exchange_value_index: {
    /**
     * Key into top-level trades
     */
    id: string;
    limits: {
      per_day?: number;
      per_week?: number;
      per_month?: number;
      per_season?: number;
    };
    value_index: number | null;
  }[];
  /**
   * valuable item id -> list of per-budget plan sets
   */
  shopping_lists: {
    [k: string]: BudgetPlans[];
  };
  overall_best_trades: BudgetBestValuePlans[];
}
export interface Item {
  name: string;
  icon: string;
  type?: "valuable" | "currency" | "material";
  acquisition_limit?: {
    per_day?: number;
    per_week?: number;
    per_month?: number;
    per_season?: number;
  };
  [k: string]: unknown;
}
export interface Trade {
  name: string;
  in?: {
    [k: string]: number;
  };
  out:
    | {
        [k: string]: number;
      }
    | (
        | {
            [k: string]: number;
          }
        | ChooseBlock
      )[];
  per_day?: number;
  per_week?: number;
  per_month?: number;
  per_season?: number;
  [k: string]: unknown;
}
export interface ChooseBlock {
  CHOOSE: {
    [k: string]: number;
  }[];
}
export interface BudgetPlans {
  budget: number;
  plans: ShoppingPlan[];
}
export interface ShoppingPlan {
  horizon: "day" | "week" | "month" | "season";
  money_spent: number;
  quantity: number;
  trades: TradeEntry[];
}
export interface TradeEntry {
  /**
   * Key into top-level trades
   */
  id: string;
  count: number;
  branches?: TradeBranch[];
}
export interface TradeBranch {
  block: number;
  picks: TradeBranchPick[];
}
export interface TradeBranchPick {
  index: number;
  count: number;
}
export interface BudgetBestValuePlans {
  budget: number;
  plans: BestValuePlan[];
}
export interface BestValuePlan {
  horizon: "day" | "week" | "month" | "season";
  money_spent: number;
  value: number;
  trades: TradeEntry[];
}
